---
title: "Data in a day"
output: html_notebook
---

```{r}
library("rpart")
library("rpart.plot")
```

## Getting the data

```{r}
df <- read.csv("mushrooms.csv")
```



## What data to we have?
```{r}
head(df)
```

```{r}
summary(df)
```


## Making predictions
Build a decision tree
```{r}
decisionTree <- rpart(class ~., data=df, method="class")
```



## How good are your predictions?

Confusion matrix
```{r}
pred <- predict(decisionTree,df,type="class")
c <- table(df$class,pred)  
print(c)
```

Percentage of predictions we got right
```{r}
(c[1,1]+c[2,2])/(sum(c))*100
```

There is also a lot of information about our tree
```{r}
summary(decisionTree)
```

But it is nice to see it
```{r}
rpart.plot(decisionTree)
```

## Avoiding overfitting
Split data into test and train
```{r}
set.seed(100)  # setting seed to reproduce results of random sampling
trainingRowIndex <- sample(1:nrow(df), 0.7*nrow(df))  # row indices for training data
trainingData <- df[trainingRowIndex, ]  # model training data
testData  <- df[-trainingRowIndex, ]   # test data
```

Re run model with training data
```{r}
decisionTree2 <- rpart(class ~., data=trainingData, method="class")
```

Look at predictions using our test data
```{r}
pred <- predict(decisionTree2,testData,type="class")
c2 <- table(testData$class,pred)  
print(c2)
print((c2[1,1]+c2[2,2])/(sum(c2))*100)
```
